### ISSUE TITLE
Add an extention for bulk loading cold data in various formats: CSV, XML, JSON

### ISSUE THREAD

**Issue by no1seman** [tarantool/cartridge-cli-extensions#10]
It's quite common task to load cold data into cluster and every time one have to make it's own wood-wheel. What if to make a framework with:
- optimal algorithm of parreling load
- support of various input formats: csv, xml, json and so on
- subset of helpers to point dest where to load data and reformat loaded data if needed
- clear runtime logging since the process is usually takes much time
- easy way to fire the process on multiple routers from multiple servers

**Comment by filonenko-mikhail** [comment]
I am so soooory, but such thing is not for this lua module. Because of several reasons:
- lua (and 2gb limit)
- complex user story in case of faults in the middle of process
- complex ddl stories
Much much gently closing.

**Comment by no1seman** [comment]
> lua (and 2gb limit) 
it's not true because GC64 is on the way
