### ISSUE TITLE
Add an extension to create core dump

### ISSUE THREAD

**Issue by no1seman** [tarantool/cartridge-cli-extensions#9]
When developing, debugging or investigating outages, it can be useful to make code dumps of running Tarantool instances. Now this procedure is not trivial, it requires connecting to the console and running a magic script, which, as always, is not at hand. It seems that for simplicity, it would be possible to include such a function in this module and then call it if necessary, with the following command:
cartridge admin --name APPNAME core_dump

**Comment by Mons** [comment]
Have no plan to evolve cartridge-cli.
